### ISSUE TITLE
What is the right way to set value for Cryptographic Algorithm in  Template Attribute?

### ISSUE THREAD

**Issue by srgg** [ThalesGroup/kmip-go#5]
I try to create a new key pair, and saw answers in https://github.com/ThalesGroup/kmip-go/issues/4

But it is still unclear to me how Cryptographic Algorithm can be set.

Here is my create key pair:

```
type CreateKeyPairRequestPayload struct {
	CommonTemplateAttribute 			kmip.TemplateAttribute
	PrivateKeyTemplateAttribute 		kmip.TemplateAttribute
	PublicKeyTemplateAttribute			kmip.TemplateAttribute
}

type CreateKeyPairResponsePayload struct {
	PrivateKeyUniqueIdentifier  	        string
	PublicKeyUniqueIdentifier  		string
	PrivateKeyTemplateAttribute 	*kmip.TemplateAttribute
	PublicKeyTemplateAttribute		*kmip.TemplateAttribute
}

type CreateHandler struct {
	Create func(ctx context.Context, payload *CreateKeyPairRequestPayload) (*CreateKeyPairResponsePayload, error)
}

func (h *CreateHandler) HandleItem(ctx context.Context, req *kmip.Request) (*kmip.ResponseBatchItem, error) {
	var payload CreateKeyPairRequestPayload
	err := req.DecodePayload(&payload)
	if err != nil {
		return nil, err
	}

	respPayload, err := h.Create(ctx, &payload)
	if err != nil {
		return nil, err
	}

	//req.IDPlaceholder = respPayload.TemplateAttribute.GetTag(kmip14.TagUniqueIdentifier, 0).(string)

	return &kmip.ResponseBatchItem{
		ResponsePayload: respPayload,
	}, nil
}

```

The command is created as follows:

```
msg := kmip.RequestMessage{
  RequestHeader: kmip.RequestHeader{
    ProtocolVersion: kmip.ProtocolVersion{
      ProtocolVersionMajor: 1,
      ProtocolVersionMinor: 2,
    },
    BatchCount:             1,
    //ClientCorrelationValue: uuid.New().String(),
  },
  BatchItem: []kmip.RequestBatchItem{
    {
      UniqueBatchItemID: biID[:],
      Operation:         kmip14.OperationCreateKeyPair,
      RequestPayload: kmip_ext.CreateKeyPairRequestPayload{
        PublicKeyTemplateAttribute: kmip.TemplateAttribute{
          Attribute: [] kmip.Attribute {
            {
              AttributeName: kmip14.TagCryptographicAlgorithm.String(),
              AttributeValue: "RSA",
            },
          },
        },
      },
    },
  },
}
```

pykmip fails to execute my request:

```
kmip_1   | 2021-04-18 07:38:21,620 kmip.server.session.00000040 INFO     Starting session: 00000040
kmip_1   | 2021-04-18 07:38:24,377 kmip.server.session.00000040 DEBUG    Request encoding: b'42007801000000c8'
kmip_1   | 2021-04-18 07:38:24,377 kmip.server.session.00000040 DEBUG    Request encoding: b'4200770100000038420069010000002042006a0200000004000000010000000042006b0200000004000000020000000042000d0200000004000000010000000042000f010000008042005c0500000004000000020000000042009308000000104bab845a1a5641bfafc3e57ff0865f95420079010000005042001f0100000000420065010000000042006e0100000038420008010000003042000a070000001643727970746f67726170686963416c676f726974686d000042000b07000000035253410000000000'
kmip_1   | 2021-04-18 07:38:24,377 kmip.server.session.00000040 DEBUG    Possible session ciphers: 6
kmip_1   | 2021-04-18 07:38:24,377 kmip.server.session.00000040 DEBUG    ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
kmip_1   | 2021-04-18 07:38:24,378 kmip.server.session.00000040 DEBUG    ('TLS_CHACHA20_POLY1305_SHA256', 'TLSv1.3', 256)
kmip_1   | 2021-04-18 07:38:24,378 kmip.server.session.00000040 DEBUG    ('TLS_AES_128_GCM_SHA256', 'TLSv1.3', 128)
kmip_1   | 2021-04-18 07:38:24,378 kmip.server.session.00000040 DEBUG    ('ECDHE-ECDSA-AES256-SHA384', 'TLSv1.2', 256)
kmip_1   | 2021-04-18 07:38:24,378 kmip.server.session.00000040 DEBUG    ('AES128-SHA256', 'TLSv1.2', 128)
kmip_1   | 2021-04-18 07:38:24,378 kmip.server.session.00000040 DEBUG    ('AES256-SHA256', 'TLSv1.2', 256)
kmip_1   | 2021-04-18 07:38:24,379 kmip.server.session.00000040 DEBUG    Session cipher selected: ('AES128-SHA256', 'TLSv1.2', 128)
kmip_1   | 2021-04-18 07:38:24,381 kmip.server.session.00000040 WARNING  Failure parsing request message.
kmip_1   | 2021-04-18 07:38:24,381 kmip.server.session.00000040 ERROR    No value type for CRYPTOGRAPHICALGORITHM
kmip_1   | Traceback (most recent call last):
kmip_1   |   File "/usr/local/lib/python3.7/site-packages/kmip/services/server/session.py", line 167, in _handle_message_loop
kmip_1   |     request.read(request_data, kmip_version=kmip_version)
kmip_1   |   File "/usr/local/lib/python3.7/site-packages/kmip/core/messages/messages.py", line 485, in read
kmip_1   |     batch_item.read(istream, kmip_version=kmip_version)
kmip_1   |   File "/usr/local/lib/python3.7/site-packages/kmip/core/messages/messages.py", line 309, in read
kmip_1   |     self.request_payload.read(tstream, kmip_version=kmip_version)
kmip_1   |   File "/usr/local/lib/python3.7/site-packages/kmip/core/messages/payloads/create_key_pair.py", line 317, in read
kmip_1   |     kmip_version=kmip_version
kmip_1   |   File "/usr/local/lib/python3.7/site-packages/kmip/core/objects.py", line 3478, in read
kmip_1   |     attribute.read(tstream, kmip_version=kmip_version)
kmip_1   |   File "/usr/local/lib/python3.7/site-packages/kmip/core/objects.py", line 117, in read
kmip_1   |     raise Exception("No value type for {}".format(enum_name))
kmip_1   | Exception: No value type for CRYPTOGRAPHICALGORITHM
kmip_1   | 2021-04-18 07:38:24,382 kmip.server.session.00000040 DEBUG    Response encoding: b'42007b01000000c842007a0100000048420069010000002042006a0200000004000000010000000042006b02000000040000000000000000420092090000000800000000607be1f042000d0200000004000000010000000042000f010000007042007f0500000004000000010000000042007e0500000004000000040000000042007d07000000444572726f722070617273696e672072657175657374206d6573736167652e2053656520736572766572206c6f677320666f72206d6f726520696e666f726d6174696f6e2e00000000'
kmip_1   | 2021-04-18 07:38:24,388 kmip.server.session.00000040 INFO     Stopping session: 00000040

```

It seems to me that attribute value should not be provided as a string, in accordance to the spec it should be enum. I'm stuck at this point and can't figure out how to provided it correctly.

Any help would be greatly appreciated.

**Comment by ansel1** [comment]
Where you set the AttributeValue, try:

     AttributeValue: kmip14.CryptographicAlgorithmRSA,

All the enum values are defined in the kmip14/kmip20 package.  Generally, the marshaler guesses whether to marshal a string to a ttlv TextString or to an enum value by looking at the tag being encoded.  If the tag has a value of Enum, and the set of allowed enum values for that tag is known, the marshaler will correctly guess that the string should be interpreted as the canonical name for one of those enum values.  But in the case of TemplateAttributes, it much more difficult for the marshaler to make that inference.  The tag is stored as a string in the AttributeName value, and the AttributeValue value is allowed to hold any type of value.

By using the enum value constants in the kmip14/kmip20 packages, you ensure the value is encoded as an Enumeration type.

**Comment by srgg** [comment]
@ansel1 Thank you for you help.

```
		BatchItem: []kmip.RequestBatchItem{
			{
				UniqueBatchItemID: biID[:],
				Operation:         kmip14.OperationCreateKeyPair,
				RequestPayload: kmip_ext.CreateKeyPairRequestPayload{
					CommonTemplateAttribute: kmip.TemplateAttribute{
						Attribute: [] kmip.Attribute {
							{
								AttributeName: kmip14.TagCryptographicAlgorithm.String(),
								AttributeValue: kmip14.CryptographicAlgorithmRSA,
							},
						},
					},
				},
			},
		},

```
I've tried but it does not work to me.. I've got the same error:

```
kmip_1     | 2021-04-20 17:57:16,781 kmip.server  INFO     Receiving incoming connection from: 192.168.80.1:59204
kmip_1     | 2021-04-20 17:57:16,782 kmip.server  INFO     Dedicating session 00000006 to 192.168.80.1:59204
kmip_1     | 2021-04-20 17:57:16,782 kmip.server.session.00000006 INFO     Starting session: 00000006
kmip_1     | 2021-04-20 17:57:16,810 kmip.server.session.00000006 DEBUG    Request encoding: b'42007801000000c8'
kmip_1     | 2021-04-20 17:57:16,810 kmip.server.session.00000006 DEBUG    Request encoding: b'4200770100000038420069010000002042006a0200000004000000010000000042006b0200000004000000020000000042000d0200000004000000010000000042000f010000008042005c05000000040000000200000000420093080000001064c001d5b9a3455ba6f89e46cbcb2eab420079010000005042001f0100000038420008010000003042000a070000001643727970746f67726170686963416c676f726974686d000042000b05000000040000000400000000420065010000000042006e0100000000'
kmip_1     | 2021-04-20 17:57:16,810 kmip.server.session.00000006 DEBUG    Possible session ciphers: 6
kmip_1     | 2021-04-20 17:57:16,810 kmip.server.session.00000006 DEBUG    ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
kmip_1     | 2021-04-20 17:57:16,810 kmip.server.session.00000006 DEBUG    ('TLS_CHACHA20_POLY1305_SHA256', 'TLSv1.3', 256)
kmip_1     | 2021-04-20 17:57:16,810 kmip.server.session.00000006 DEBUG    ('TLS_AES_128_GCM_SHA256', 'TLSv1.3', 128)
kmip_1     | 2021-04-20 17:57:16,811 kmip.server.session.00000006 DEBUG    ('AES128-SHA256', 'TLSv1.2', 128)
kmip_1     | 2021-04-20 17:57:16,811 kmip.server.session.00000006 DEBUG    ('AES256-SHA256', 'TLSv1.2', 256)
kmip_1     | 2021-04-20 17:57:16,811 kmip.server.session.00000006 DEBUG    ('ECDHE-ECDSA-AES256-SHA384', 'TLSv1.2', 256)
kmip_1     | 2021-04-20 17:57:16,811 kmip.server.session.00000006 DEBUG    Session cipher selected: ('AES128-SHA256', 'TLSv1.2', 128)
kmip_1     | 2021-04-20 17:57:16,812 kmip.server.session.00000006 WARNING  Failure parsing request message.
kmip_1     | 2021-04-20 17:57:16,813 kmip.server.session.00000006 ERROR    No value type for CRYPTOGRAPHICALGORITHM
kmip_1     | Traceback (most recent call last):
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/services/server/session.py", line 167, in _handle_message_loop
kmip_1     |     request.read(request_data, kmip_version=kmip_version)
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/messages/messages.py", line 485, in read
kmip_1     |     batch_item.read(istream, kmip_version=kmip_version)
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/messages/messages.py", line 309, in read
kmip_1     |     self.request_payload.read(tstream, kmip_version=kmip_version)
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/messages/payloads/create_key_pair.py", line 266, in read
kmip_1     |     kmip_version=kmip_version
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/objects.py", line 3478, in read
kmip_1     |     attribute.read(tstream, kmip_version=kmip_version)
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/objects.py", line 117, in read
kmip_1     |     raise Exception("No value type for {}".format(enum_name))
kmip_1     | Exception: No value type for CRYPTOGRAPHICALGORITHM
kmip_1     | 2021-04-20 17:57:16,814 kmip.server.session.00000006 DEBUG    Response encoding: b'42007b01000000c842007a0100000048420069010000002042006a0200000004000000010000000042006b02000000040000000000000000420092090000000800000000607f15fc42000d0200000004000000010000000042000f010000007042007f0500000004000000010000000042007e0500000004000000040000000042007d07000000444572726f722070617273696e672072657175657374206d6573736167652e2053656520736572766572206c6f677320666f72206d6f726520696e666f726d6174696f6e2e00000000'
kmip_1     | 2021-04-20 17:57:16,819 kmip.server.session.00000006 INFO     Stopping session: 00000006
```

**Comment by ansel1** [comment]
Yeah, I see the problem.  The KMIP spec calls for the values of AttributeName to the full, "canonical" name of the attribute from the spec, including spaces.  Like "Cryptographic Algorithm".  I assumed it was supposed to be the "normalized", camelCase version of the name used in most other places.  

I've pushed changes that add a Tag.CanonicalName() method, which is what you need to use instead of Tag.String() in this instance.  I also added a TemplateAttribute.Append(Tag, interface{}) method to simplify adding attributes to TemplateAttribute.

I also defined the CreateKeyPairRequestPayload and CreateKeyPairResponsePayload struct, and added a TestCreateKeyPair() test which demonstrates a successful Create Key Pair operation against pykmip.

**Comment by srgg** [comment]
That works! Thank you for your help, it will be much longer to get this fixed without our help.
