### ISSUE TITLE
What is the right way to set value for Name in Template Attribute?

### ISSUE THREAD

**Issue by srgg** [ThalesGroup/kmip-go#6]
I try to create a new key with a specific Name ( 3.1.3    Use-case: Create / Locate / Get / Destroy  from https://docs.oasis-open.org/kmip/usecases/v1.0/cd05/kmip-usecases-1.0-cd-05.html)

```
	request := kmip.CreateRequestPayload{
		ObjectType: kmip14.ObjectTypeSymmetricKey,
		TemplateAttribute: kmip.TemplateAttribute{},
	}
	request.TemplateAttribute.Append(kmip14.TagCryptographicAlgorithm, kmip14.CryptographicAlgorithmAES)
	request.TemplateAttribute.Append(kmip14.TagCryptographicLength, length)
	request	.TemplateAttribute.Append(kmip14.TagCryptographicUsageMask, kmip14.CryptographicUsageMaskEncrypt|kmip14.CryptographicUsageMaskDecrypt)
	request.TemplateAttribute.Append(kmip14.TagName, "test2")

```

But pykmip fails to execute my request:

```
kmip_1     | 2021-04-22 15:26:26,603 kmip.server.session.00000006 INFO     Starting session: 00000006
kmip_1     | 2021-04-22 15:26:26,631 kmip.server.session.00000006 DEBUG    Request encoding: b'4200780100000160'
kmip_1     | 2021-04-22 15:26:26,631 kmip.server.session.00000006 DEBUG    Request encoding: b'4200770100000038420069010000002042006a0200000004000000010000000042006b0200000004000000040000000042000d0200000004000000010000000042000f010000011842005c050000000400000001000000004200930800000010f7edb310b31a4517a6168e673d4b07a042007901000000e84200570500000004000000020000000042009101000000d0420008010000003042000a070000001743727970746f6772617068696320416c676f726974686d0042000b05000000040000000300000000420008010000003042000a070000001443727970746f67726170686963204c656e6774680000000042000b02000000040000010000000000420008010000003042000a070000001843727970746f67726170686963205573616765204d61736b42000b02000000040000000c00000000420008010000002042000a07000000044e616d650000000042000b07000000057465737432000000'
kmip_1     | 2021-04-22 15:26:26,632 kmip.server.session.00000006 DEBUG    Possible session ciphers: 6
kmip_1     | 2021-04-22 15:26:26,632 kmip.server.session.00000006 DEBUG    ('TLS_AES_256_GCM_SHA384', 'TLSv1.3', 256)
kmip_1     | 2021-04-22 15:26:26,632 kmip.server.session.00000006 DEBUG    ('TLS_CHACHA20_POLY1305_SHA256', 'TLSv1.3', 256)
kmip_1     | 2021-04-22 15:26:26,632 kmip.server.session.00000006 DEBUG    ('TLS_AES_128_GCM_SHA256', 'TLSv1.3', 128)
kmip_1     | 2021-04-22 15:26:26,632 kmip.server.session.00000006 DEBUG    ('AES256-SHA256', 'TLSv1.2', 256)
kmip_1     | 2021-04-22 15:26:26,632 kmip.server.session.00000006 DEBUG    ('ECDHE-ECDSA-AES256-SHA384', 'TLSv1.2', 256)
kmip_1     | 2021-04-22 15:26:26,632 kmip.server.session.00000006 DEBUG    ('AES128-SHA256', 'TLSv1.2', 128)
kmip_1     | 2021-04-22 15:26:26,632 kmip.server.session.00000006 DEBUG    Session cipher selected: ('AES128-SHA256', 'TLSv1.2', 128)
kmip_1     | 2021-04-22 15:26:26,634 kmip.server.session.00000006 WARNING  Failure parsing request message.
kmip_1     | 2021-04-22 15:26:26,634 kmip.server.session.00000006 ERROR    Tried to read Base.type: expected 1, received 7
kmip_1     | Traceback (most recent call last):
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/services/server/session.py", line 167, in _handle_message_loop
kmip_1     |     request.read(request_data, kmip_version=kmip_version)
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/messages/messages.py", line 485, in read
kmip_1     |     batch_item.read(istream, kmip_version=kmip_version)
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/messages/messages.py", line 309, in read
kmip_1     |     self.request_payload.read(tstream, kmip_version=kmip_version)
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/messages/payloads/create.py", line 165, in read
kmip_1     |     kmip_version=kmip_version
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/objects.py", line 3478, in read
kmip_1     |     attribute.read(tstream, kmip_version=kmip_version)
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/objects.py", line 120, in read
kmip_1     |     self.attribute_value.read(tstream, kmip_version=kmip_version)
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/attributes.py", line 115, in read
kmip_1     |     super(Name, self).read(istream, kmip_version=kmip_version)
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/primitives.py", line 106, in read
kmip_1     |     self.read_type(istream)
kmip_1     |   File "/usr/local/lib/python3.7/site-packages/kmip/core/primitives.py", line 84, in read_type
kmip_1     |     typ
kmip_1     | kmip.core.exceptions.ReadValueError: Tried to read Base.type: expected 1, received 7
kmip_1     | 2021-04-22 15:26:26,635 kmip.server.session.00000006 DEBUG    Response encoding: b'42007b01000000c842007a0100000048420069010000002042006a0200000004000000010000000042006b02000000040000000000000000420092090000000800000000608195a242000d0200000004000000010000000042000f010000007042007f0500000004000000010000000042007e0500000004000000040000000042007d07000000444572726f722070617273696e672072657175657374206d6573736167652e2053656520736572766572206c6f677320666f72206d6f726520696e666f726d6174696f6e2e00000000'
kmip_1     | 2021-04-22 15:26:26,639 kmip.server.session.00000006 INFO     Stopping session: 00000006

```

It seems that I need to add Name Type, but can't figure out how I can do this.

Any help would be greatly appreciated.

**Comment by ansel1** [comment]
The value for Name is a struct, not a string.  See here in the spec: http://docs.oasis-open.org/kmip/spec/v1.0/os/kmip-spec-1.0-os.html#_Toc262581174

I just pushed a working test case for Create.  See TestCreateKey.

**Comment by ansel1** [comment]
Also, I tried making the test case match the use case exactly, but pykmip doesn't support DES, and doesn't support the ContactInformation attribute.

To run that use case, run `make up` then `go test -run TestCreateKey`.

**Comment by srgg** [comment]
Am sorry, forgot to thank you! It works like a charm!
